### ISSUE TITLE
requirements error for install

### ISSUE THREAD

**Issue by map2085** [ratschlab/RiboDiff#2]
`python setup.py   build`

works fine

`python setup.py   install`

 produces an error:

>   File "/path/to/python-2.7/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
>     requirement_string[e.loc:e.loc + 8]))
> pkg_resources._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'(>=2011k'"

same error if I run     `python setup.py   test`

**Comment by vipints** [comment]
Let me know the version of the `setuptools` you are using. Looks like an issue with the same.

**Comment by map2085** [comment]
`$ easy_install  --version`

> setuptools 20.2 from /path/to/python-2.7/lib/python2.7/site-packages (Python 2.7)

**Comment by map2085** [comment]
`$ pip install setuptools  -U`

you were right.  upgrading setuptools did the trick.
It works now,
Thank you!
