### ISSUE TITLE
local variable 'yhat' referenced before assignment

### ISSUE THREAD

**Issue by nelson42** [ratschlab/RiboDiff#3]
I've installed RiboDiff and have managed to run the analysis on the test data with no problems, however when I attempt to use my own data I hit the following error
```
nelson~/Downloads/RiboDiff> python ./scripts/TE.py -e ~/mRNA_fastqs/designG -c ~/mRNA_fastqs/Gcounts -o ./tests2/output.tab -d 0 -r 1 -p 1
*************************
Read input files: Done.
6909 Gene(s) to be tested.
*************************
Library size:
['Ribo_untreated' 'Ribo_-G']
[ 0.671  1.424]
['Total_untreated' 'Total_-G']
[ 0.76   1.278]
*************************
Start to estimate raw dispersions.
0 genes finished...
Traceback (most recent call last):
  File "./scripts/TE.py", line 81, in <module>
    main()
  File "./scripts/TE.py", line 48, in main
    data = ed.estimate_disp(data, opts)
  File "/usr/local/lib/python2.7/dist-packages/RiboDiff-0.2.1-py2.7.egg/ribodiff/estimatedisp.py", line 31, in estimate_disp
    data = rd.disper_raw_scalar(data, opts)
  File "/usr/local/lib/python2.7/dist-packages/RiboDiff-0.2.1-py2.7.egg/ribodiff/rawdisp.py", line 226, in disper_raw_scalar
    muRaw[i, :] = yhat
UnboundLocalError: local variable 'yhat' referenced before assignment
```
The heads of the input files are as follows:
```
nelson~/Downloads/RiboDiff> head ~/mRNA_fastqs/designG
Samples,Data_Type,Conditions
Ribo_untreated,Ribo-Seq,Control
Ribo_-G,Ribo-Seq,Treated
Total_untreated,RNA-Seq,Control
Total_-G,RNA-Seq,Treated
nelson~/Downloads/RiboDiff> head ~/mRNA_fastqs/Gcounts
ID	Ribo_untreated	Ribo_-G	Total_untreated	Total_-G
YAL068C	1	8	22	25
YAL067W-A	0	0	1	4
YAL067C	3	9	12	13
YAL066W	0	0	0	0
YAL065C	0	5	33	66
YAL064W-B	1	85	25	65
YAL064C-A	0	0	10	31
YAL064W	0	0	3	1
YAL063C-A	0	1	1	5
```
Any idea what I might be doing wrong here?

Thanks very much,

Mike

**Comment by yizhong** [comment]
Hi Mike,

I believe the error message you saw was caused by the single replicate in the input file. If you add another replicate to any of the four samples, it should work properly. For example, you can just duplicate the count column of Ribo_untreated to Ribo_untreated2, modify the designG matrix file accordingly, and run it again. This excludes the error was caused by the format of the inputs. 

Without any replicates in both Ribo-Seq and RNA-Seq data, RiboDiff is not able to estimate the dispersion parameter. 

Thanks,
Yi

**Comment by nelson42** [comment]
Hi Yi,

Thanks for your quick response on this.
Is it possible that the software would still fail if the to calculate dispersions with identical results?
I duplicated the columns but still encountered the same error, however by adding 1 to the counts in the duplicated column everything now seems to work (though now not with "real" data). 
I should have replicate data for these experiments eventually so if the identical columns are causing the problem then I should have a war around this soon!

Cheers,
Mike

**Comment by yizhong** [comment]
I tried a count dataset which includes only one identical count column of a sample. RiboDiff didn't throw out any error message. I guess your data is in a rare case. 
But as you will have replicates, this error shouldn't appear later. If you have other questions, let us know. 

Thank you.
