### ISSUE TITLE
p-value is NAN for some genes

### ISSUE THREAD

**Issue by yancychy** [ratschlab/RiboDiff#6]
Hi Yizhong,
     When I run the test data, there are 19 genes with NAN values. I just used the following command:
python  scripts/TE.py -e  tests/experimental_design.csv -c  tests/gene_count_table.tab -o  tests/toy.res.tab -d 0 -r 1 -p 1
      Can you give me some suggestions on this problem? Thanks very much.   
    
geneIDs	disper	pval	padj	TEControl	TETreated	log2FC_TE(Treated vs Control) 
ENSG00000164484	nan	nan	nan	nan	0.004131582782477473	0.004124170124065996	-0.002590728798436359
ENSG00000175820	nan	nan	nan	nan	0.01286982788096814	0.035249157624712854	1.4535960214554677
ENSG00000256892	nan	nan	nan	nan	9.263046968800072	13.935174559369592	0.5891723405274973
ENSG00000227268	nan	nan	nan	nan	0.03152367124596093	0.019362640270852362	-0.7031598702836552
ENSG00000107968	nan	nan	nan	nan	0.0025005284902858793	0.006701083245920227	1.4221612866982847
ENSG00000129038	nan	nan	nan	nan	0.017966164873857857	0.0067325243951978486	-1.4160630210893865
ENSG00000143630	nan	nan	nan	nan	0.0012051315409346373	0.002406871954108295	0.9979687660921162
ENSG00000197948	nan	nan	nan	nan	0.002032402894155271	0.002150167271600479	0.08126247453973079
ENSG00000183876	nan	nan	nan	nan	357.6052427771633	524.0003479873238	0.5511998821206685

The errors are following:
scipy/optimize/_minimize.py:761: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  "defaulting to absolute tolerance.", RuntimeWarning)

RiboDiff-0.2.1-py2.7.egg/ribodiff/adjdisp.py:18: RuntimeWarning: invalid value encountered in log
  logprior = (np.log(disp) - np.log(dispFitted)) ** 2 / (2 * varPrior ** 2)

statsmodels/genmod/generalized_linear_model.py:302: DomainWarning: The identity link function does not respect the domain of the Gamma family.
  DomainWarning)

**Comment by yizhong** [comment]
I don't see your issue. Please describe it ...

**Comment by yizhong** [comment]
Is this your questions:

==========
Hi Yizhong,
When I run the test data, there are 19 genes with NAN values. I just used the following command:
python scripts/TE.py -e tests/experimental_design.csv -c tests/gene_count_table.tab -o tests/toy.res.tab -d 0 -r 1 -p 1
Can you give me some suggestions on this problem? Thanks very much.

geneIDs	disper	pval	padj	TEControl	TETreated	log2FC_TE(Treated vs Control)
ENSG00000164484	nan	nan	nan	nan	0.004131582782477473	0.004124170124065996	-0.002590728798436359
ENSG00000175820	nan	nan	nan	nan	0.01286982788096814	0.035249157624712854	1.4535960214554677
ENSG00000256892	nan	nan	nan	nan	9.263046968800072	13.935174559369592	0.5891723405274973
==========

In the test data there are several genes with very low Ribo-seq read counts. RiboDiff doesn't accept those genes by default. If you really want to test those genes, you could add argument "-s" to your command. It sets the minimal read count for both Ribo-seq and RNA-seq. "-s 1" will allow RiboDiff to test any genes that have 1 read count in any replicate of Ribo and RNA.

**Comment by yizhong** [comment]
Is this your question:

=======================
Hi Yizhong,
When I run the test data, there are 19 genes with NAN values. I just used the following command:
python scripts/TE.py -e tests/experimental_design.csv -c tests/gene_count_table.tab -o tests/toy.res.tab -d 0 -r 1 -p 1
Can you give me some suggestions on this problem? Thanks very much.

geneIDs	disper	pval	padj	TEControl	TETreated	log2FC_TE(Treated vs Control)
ENSG00000164484	nan	nan	nan	nan	0.004131582782477473	0.004124170124065996	-0.002590728798436359
ENSG00000175820	nan	nan	nan	nan	0.01286982788096814	0.035249157624712854	1.4535960214554677
......
=======================

In the test data, there are a few genes with very low read counts for Ribo-seq. By default, RiboDiff does not test those genes for TE change. If you really want to have them being tested, you could add another argument to your command: '-s'. For example, '-s 1' will allow RiboDiff to test any gene that have 1 read count in any replicate in both Ribo-seq and RNA-seq data. Obviously, setting this cutoff too low is not recommended.

**Comment by yancychy** [comment]
Thanks Yizhong. I will try to filter the low read counts first.
